const {
  run, 
  // ethers, 
  // network,
} = require("hardhat")

/*
  From Hardhat docs: Verifying a contract means making its source code public, along with the compiler settings you used, which allows anyone to compile it and compare the generated bytecode with the one that is deployed on-chain. Doing this is important in an open platform like Ethereum.
*/
async function verify(contractAddress, args) {
  console.log("Verifying contract...", {contractAddress}, {args})
  try {
    await run("verify:verify", {
      address: contractAddress,
      constructorArguments: args,
    })
  } catch (e) {
    console.log('catching test, temp:', e)
    const lowerCaseMessage = e.message?.toLowerCase()
    if (
      lowerCaseMessage.includes("already") &&
      lowerCaseMessage.includes("verified") 
    ) {
      console.log("Already verified")
    } 
    else {
      console.log(e)
    }
  }
}

module.exports = {verify}